TOKEN = "YOUR BOT TOKEN"
TON_API_KEY = 'YOUR https://tonapi.io/ API KEY'
TONCENTER_API_KEY = "YOUR https://toncenter.com/ API KEY"
DEPOSIT_ADDRESS = "YOUR V4R2 ADDRESS FOR DEPOSIT"
DEPOSIT_ADDRESS_VERSION = 'v4r2'
OPEN_MASTER_ADDRESS = 'EQDf84FT8tdHZeI2-LXdb8gPMRqHRSABrmi8jI7MzvVpGJKZ'
MARKET_MAKER_FEE = 0.01
MIN_DEAL = 2
MARKET_DEAL_PRICE = 0.1
DEPOSIT_ADDRESS_MNEMONIC = ['YOUR', 'MNEMONIC', 'PHRASE']
WITHDRAW_FEE = 1.5
MIN_WITHDRAW = 1.0
RUN_IN_MAINNET = True
SUPPORT_USERNAME = '@TGSUPPORTUNAME'
BOT_ID = 6580078627


if RUN_IN_MAINNET:
    API_BASE_URL = 'https://toncenter.com'
else:
    API_BASE_URL = 'https://testnet.toncenter.com'
